function getCart(){return JSON.parse(localStorage.getItem('perfectHomeCart')||'[]')}
function saveCart(c){localStorage.setItem('perfectHomeCart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){const el=document.getElementById('cartCount');if(el)el.textContent=getCart().reduce((s,x)=>s+x.qty,0)}
function addToCart(id,qty=1){const c=getCart();const item=c.find(x=>x.id===id);if(item)item.qty+=qty;else c.push({id,qty});saveCart(c);toast('Added to your cart ✓')}
function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function performSearch(){const q=document.getElementById('searchInput')?.value.trim();if(q)location.href='products.html?search='+encodeURIComponent(q);else location.href='products.html'}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();const s=document.getElementById('searchInput');if(s)s.addEventListener('keydown',e=>{if(e.key==='Enter')performSearch()});if(document.getElementById('featured'))document.getElementById('featured').innerHTML=PRODUCTS.slice(30,36).concat(PRODUCTS.slice(0,2)).map(productCard).join('');if(document.getElementById('products'))initShop()});
let currentCategory='All';
function initShop(){const p=new URLSearchParams(location.search);currentCategory=p.get('category')||'All';const q=p.get('search');if(q){const s=document.getElementById('searchInput');if(s)s.value=q}renderProducts()}
function setCategory(c){currentCategory=c;renderProducts()}
function renderProducts(){const root=document.getElementById('products');if(!root)return;const q=new URLSearchParams(location.search).get('search')||document.getElementById('searchInput')?.value||'';const term=q.toLowerCase();let list=PRODUCTS.filter(p=>(currentCategory==='All'||p.cat===currentCategory)&&(!term||(p.name+' '+p.cat+' '+p.desc).toLowerCase().includes(term)));const max=document.querySelector('input[name=price]:checked')?.value;if(max&&max!=='all')list=list.filter(p=>p.price<=+max);const sort=document.getElementById('sort')?.value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);document.getElementById('resultText').textContent=`${list.length} products${currentCategory!=='All'?' in '+currentCategory:''}${term?' matching “'+q+'”':''}`;root.innerHTML=list.length?list.map(productCard).join(''):`<div class="empty-results"><div>🔎</div><h2>No furniture found</h2><p>Try another search or category.</p><a class="btn primary" href="products.html">View all products</a></div>`}
