const PRODUCTS = [
{id:1,name:'Royal 3-Door Wooden Cupboard',cat:'Cupboards',price:18999,old:22999,rating:4.8,img:'images/cupboard-1.svg',desc:'Spacious solid-finish wardrobe with three doors, adjustable shelves and a premium walnut look.'},
{id:2,name:'Modern 2-Door Wardrobe',cat:'Cupboards',price:12999,old:15999,rating:4.6,img:'images/cupboard-2.svg',desc:'Clean modern storage with generous hanging space and smooth-finish doors.'},
{id:3,name:'Premium Sliding Wardrobe',cat:'Cupboards',price:24999,old:29999,rating:4.9,img:'images/cupboard-1.svg',desc:'Contemporary sliding wardrobe designed for premium bedrooms and compact spaces.'},
{id:4,name:'Classic 4-Door Cupboard',cat:'Cupboards',price:21999,old:26999,rating:4.7,img:'images/cupboard-2.svg',desc:'Large family wardrobe with four doors and organized storage compartments.'},
{id:5,name:'Urban Storage Cabinet',cat:'Cupboards',price:9999,old:12999,rating:4.5,img:'images/cupboard-1.svg',desc:'Versatile cabinet for living rooms, bedrooms and home offices.'},
{id:6,name:'Designer Glass Door Wardrobe',cat:'Cupboards',price:27999,old:32999,rating:4.8,img:'images/cupboard-2.svg',desc:'Statement wardrobe with glass-front detailing and elegant internal organization.'},
{id:7,name:'Executive Study Table',cat:'Tables',price:8499,old:10999,rating:4.8,img:'images/table-1.svg',desc:'Spacious work desk with drawers and a refined wood finish.'},
{id:8,name:'Modern Computer Table',cat:'Tables',price:6499,old:7999,rating:4.6,img:'images/table-2.svg',desc:'Compact computer workstation for home offices and study rooms.'},
{id:9,name:'Wooden Office Table',cat:'Tables',price:7299,old:8999,rating:4.7,img:'images/table-1.svg',desc:'Strong everyday office desk with cable-friendly workspace.'},
{id:10,name:'Compact Writing Table',cat:'Tables',price:4999,old:5999,rating:4.5,img:'images/table-2.svg',desc:'Minimal writing desk for bedrooms, study corners and apartments.'},
{id:11,name:'Premium Console Table',cat:'Tables',price:9499,old:11999,rating:4.8,img:'images/table-1.svg',desc:'Elegant console table for entryways and living rooms.'},
{id:12,name:'Designer Side Table',cat:'Tables',price:3499,old:4499,rating:4.4,img:'images/table-2.svg',desc:'Small designer side table with a warm wood character.'},
{id:13,name:'Premium Office Chair',cat:'Chairs',price:8999,old:11999,rating:4.8,img:'images/chair-1.svg',desc:'Ergonomic cushioned chair with supportive backrest and premium upholstery.'},
{id:14,name:'Wooden Dining Chair',cat:'Chairs',price:2999,old:3999,rating:4.6,img:'images/chair-2.svg',desc:'Classic wooden chair designed for everyday dining comfort.'},
{id:15,name:'Executive Leather Chair',cat:'Chairs',price:7499,old:9499,rating:4.7,img:'images/chair-1.svg',desc:'High-back executive chair with soft leather-look upholstery.'},
{id:16,name:'Lounge Chair',cat:'Chairs',price:6999,old:8999,rating:4.7,img:'images/chair-2.svg',desc:'Relaxed lounge chair that adds a cozy accent to any room.'},
{id:17,name:'Modern Accent Chair',cat:'Chairs',price:5799,old:6999,rating:4.5,img:'images/chair-1.svg',desc:'Contemporary accent seating with a soft, inviting profile.'},
{id:18,name:'Study Chair',cat:'Chairs',price:3999,old:4999,rating:4.4,img:'images/chair-2.svg',desc:'Comfortable everyday study chair for focused work sessions.'},
{id:19,name:'4-Seater Dining Table',cat:'Dining Tables',price:11999,old:14999,rating:4.8,img:'images/dining-1.svg',desc:'Warm wooden dining table perfect for compact family dining.'},
{id:20,name:'6-Seater Dining Table',cat:'Dining Tables',price:16999,old:20999,rating:4.8,img:'images/dining-2.svg',desc:'Spacious six-seater table built for family meals and celebrations.'},
{id:21,name:'6-Seater Premium Dining Set',cat:'Dining Tables',price:22999,old:27999,rating:4.9,img:'images/dining-1.svg',desc:'Complete premium dining set with coordinated chairs and table.'},
{id:22,name:'8-Seater Family Dining Table',cat:'Dining Tables',price:24999,old:29999,rating:4.7,img:'images/dining-2.svg',desc:'Large family table with a substantial solid-wood appearance.'},
{id:23,name:'Marble Top Dining Table',cat:'Dining Tables',price:19999,old:24999,rating:4.8,img:'images/dining-1.svg',desc:'Elegant marble-look top paired with a strong contemporary base.'},
{id:24,name:'Solid Wood Dining Table',cat:'Dining Tables',price:18999,old:23999,rating:4.9,img:'images/dining-2.svg',desc:'Timeless solid-wood dining table with natural character.'},
{id:25,name:'3-Tier Shoe Rack',cat:'Shoes Rack',price:2499,old:3299,rating:4.5,img:'images/shoe-1.svg',desc:'Compact three-tier rack for everyday footwear near your entrance.'},
{id:26,name:'4-Door Shoe Cabinet',cat:'Shoes Rack',price:6999,old:8999,rating:4.7,img:'images/shoe-2.svg',desc:'Closed shoe storage cabinet that keeps your entryway clean and organized.'},
{id:27,name:'Wooden Shoe Rack',cat:'Shoes Rack',price:3999,old:4999,rating:4.6,img:'images/shoe-1.svg',desc:'Warm wooden rack with multiple open shelves.'},
{id:28,name:'Premium Storage Shoe Cabinet',cat:'Shoes Rack',price:8499,old:10999,rating:4.8,img:'images/shoe-2.svg',desc:'Premium closed storage with a clean contemporary silhouette.'},
{id:29,name:'Slim Entryway Shoe Rack',cat:'Shoes Rack',price:2999,old:3799,rating:4.5,img:'images/shoe-1.svg',desc:'Slim profile rack made for smaller entryways.'},
{id:30,name:'Large Family Shoe Cabinet',cat:'Shoes Rack',price:9499,old:11999,rating:4.7,img:'images/shoe-2.svg',desc:'High-capacity cabinet for larger families and extensive footwear collections.'},
{id:31,name:'King Size Wooden Bed',cat:'Wooden Beds',price:22999,old:27999,rating:4.9,img:'images/bed-1.svg',desc:'Elegant king-size wooden bed with a strong frame and timeless headboard.'},
{id:32,name:'Queen Size Wooden Bed',cat:'Wooden Beds',price:17999,old:21999,rating:4.8,img:'images/bed-2.svg',desc:'Comfortable queen-size bed with a warm natural finish.'},
{id:33,name:'Storage King Bed',cat:'Wooden Beds',price:26999,old:31999,rating:4.9,img:'images/bed-1.svg',desc:'King bed with practical under-bed storage and a refined wooden finish.'},
{id:34,name:'Hydraulic Storage Bed',cat:'Wooden Beds',price:29999,old:35999,rating:4.8,img:'images/bed-2.svg',desc:'Easy-lift hydraulic storage bed for maximum bedroom organization.'},
{id:35,name:'Solid Wood Designer Bed',cat:'Wooden Beds',price:24999,old:29999,rating:4.9,img:'images/bed-1.svg',desc:'Designer solid-wood frame with beautiful craftsmanship and strong construction.'},
{id:36,name:'Premium Upholstered Wooden Bed',cat:'Wooden Beds',price:27999,old:33999,rating:4.8,img:'images/bed-2.svg',desc:'Premium upholstered headboard combined with a durable wooden frame.'}
];
function money(n){return '₹'+n.toLocaleString('en-IN')}
function productCard(p){return `<article class="product-card"><a href="product-details.html?id=${p.id}" class="product-img"><img src="${p.img}" alt="${p.name}"><span class="discount">${Math.round((1-p.price/p.old)*100)}% OFF</span></a><div class="product-info"><small>${p.cat}</small><a class="product-name" href="product-details.html?id=${p.id}">${p.name}</a><div class="rating">★ ${p.rating} <span>· 120+ reviews</span></div><div class="price">${money(p.price)} <del>${money(p.old)}</del></div><button class="add-btn" onclick="addToCart(${p.id})">Add to cart</button></div></article>`}
